import { 
  mdiFileTree,
  mdiLoading,
  mdiCogOutline,
  mdiAccountOutline,
  mdiFolderEditOutline,
  mdiChevronUp,
  mdiChevronDown,
  mdiFormatBold,
  mdiFormatItalic,
  mdiFormatStrikethroughVariant,
  mdiInformationOutline,
  mdiCalendarCheckOutline,
  mdiInvertColors,
  mdiFormatText,
  mdiFormatListChecks,
  mdiShapeOutline,
  mdiPowerPlugOutline,
  mdiCloseBoxOutline,
  mdiShapeRectanglePlus,
  mdiLogoutVariant,
  mdiEmailOutline,
  mdiFingerprint,
  mdiBellOutline,
  mdiBellOffOutline,
  mdiForumOutline,
  mdiMagnify,
  mdiMenuDownOutline,
  mdiPlusCircleOutline,
  mdiAccountPlusOutline,
  mdiDotsHorizontal,
  mdiHeartOutline,
  mdiCommentOutline,
  mdiPackageVariantClosed,
  mdiCloseCircleOutline
} from '@mdi/js'
 
export default (context, inject) => {
   const icons = { 
    mdiFileTree,
    mdiLoading,
    mdiCogOutline,
    mdiAccountOutline,
    mdiFolderEditOutline,
    mdiChevronUp,
    mdiChevronDown,
    mdiFormatBold,
    mdiFormatItalic,
    mdiFormatStrikethroughVariant,
    mdiInformationOutline,
    mdiCalendarCheckOutline,
    mdiInvertColors,
    mdiFormatText,
    mdiFormatListChecks,
    mdiShapeOutline,
    mdiPowerPlugOutline,
    mdiCloseBoxOutline,
    mdiShapeRectanglePlus,
    mdiLogoutVariant,
    mdiEmailOutline,
    mdiFingerprint,
    mdiBellOutline,
    mdiForumOutline,
    mdiMagnify,
    mdiMenuDownOutline,
    mdiPlusCircleOutline,
    mdiAccountPlusOutline,
    mdiDotsHorizontal,
    mdiHeartOutline,
    mdiCommentOutline,
    mdiBellOffOutline,
    mdiPackageVariantClosed,
    mdiCloseCircleOutline
  }

  inject('icons', icons)
  context.$icons = icons
}